// ESLint 10 flat config, replacing .eslintrc.cjs and .eslintignore, neither of
// which ESLint 10 reads any more. Ignore patterns must live here now.
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default [
	{
		// A trailing /** is required to ignore a directory's contents. Only
		// paths ESLint would otherwise walk are listed - it already skips
		// node_modules, and only looks at js/cjs/mjs and svelte files.
		ignores: [
			'docs/**',
			'.svelte-kit/**',
			'tools/**',
			// generated by the Nuke build from the blog post front matter
			'**/Posts.js',
			'**/SearchData.js'
		]
	},

	js.configs.recommended,
	...svelte.configs.recommended,

	{
		// ecmaVersion and sourceType are left at ESLint 10's defaults (latest,
		// and module for a "type": "module" package).
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		}
	},

	// Must come last so formatting rules are switched off rather than back on.
	prettier,
	...svelte.configs.prettier
];
