// ESLint 10 flat config, replacing .eslintrc.cjs and .eslintignore, neither of
// which ESLint 10 reads any more. Ignore patterns must live here now.
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default [
	{
		// Mirrors the old .eslintignore. Paths are relative to this file, and a
		// trailing /** is required to ignore a directory's contents.
		ignores: [
			'docs/**',
			'.svelte-kit/**',
			'package/**',
			'tools/**',
			'**/.DS_Store',
			'**/.env',
			'**/.env.*',
			'!**/.env.example',
			// generated by the Nuke build from the blog post front matter
			'**/Posts.js',
			'**/SearchData.js'
		]
	},

	js.configs.recommended,
	...svelte.configs.recommended,

	{
		languageOptions: {
			ecmaVersion: 2020,
			sourceType: 'module',
			globals: { ...globals.browser, ...globals.node }
		}
	},

	{
		rules: {
			// New in eslint-plugin-svelte 3's recommended set; 14 hits across the
			// site. Keying an each block changes how Svelte reconciles the list,
			// and a duplicate key throws at runtime, so this is an application
			// change rather than a lint-toolchain one. Deferred deliberately, not
			// dismissed - turn this back on and fix the blocks in their own change.
			'svelte/require-each-key': 'off'
		}
	},

	// Must come last so formatting rules are switched off rather than back on.
	prettier,
	...svelte.configs.prettier
];
