// WARNING: This file is generated by tools and should not be modified by hand.

/** Association between Post id and component. */
export const Posts = [];
Posts['86f85de2-571b-4df4-9b39-140907351b5d'] = () => import ('$lib/blog/posts/BirthOfANewNewBlog.svelte');

/** Association between Post id and its metadata. */
export const PostMetadata = [];
PostMetadata['86f85de2-571b-4df4-9b39-140907351b5d'] = { title: `Birth of a new blog!`, id: '86f85de2-571b-4df4-9b39-140907351b5d', posted: '2/22/2024', lastModified: '2/22/2024', summary: `So I created a simple blogging platform for my portfolio site and here's what I'm going to do with it...`, tags: [ `blog`, `housekeeping`, `announcement` ] };

/** Association between Post id and and its previous and next post. */
export const PostAdjacency = [];
PostAdjacency['86f85de2-571b-4df4-9b39-140907351b5d'] = { previous: null, next: null };

/** Latest Post Id. */
export const LatestPostId = '86f85de2-571b-4df4-9b39-140907351b5d';
