// WARNING: This file is generated by tools and should not be modified by hand.

/**
 * @typedef {import('$lib/types').PostMetadata} PostMetadata
 * @typedef {import('$lib/types').PostAdjacency} PostAdjacency
 * @typedef {import('svelte').SvelteComponent} SvelteComponent
 */

/**
 * Association between Post id and component.
 * @type {Object.<string, function(): Promise<SvelteComponent>>)}
 */
export const Posts = [];
Posts['86f85de2-571b-4df4-9b39-140907351b5d'] = () => import ('$lib/blog/posts/BirthOfANewNewBlog.svelte');
Posts['124520dd-56cd-4b13-808f-7e54e885925a'] = () => import ('$lib/blog/posts/HowTheBlogWorks.svelte');

/**
 * Association between Post id and its metadata.
 * @type {Object.<string, PostMetadata>}
 */
export const PostMetadata = [];
PostMetadata['86f85de2-571b-4df4-9b39-140907351b5d'] = { title: `Birth of a new blog!`, id: '86f85de2-571b-4df4-9b39-140907351b5d', posted: '2/22/2024', lastModified: '3/1/2024', summary: `So I created a simple blogging platform for my portfolio site and here's what I'm going to do with it...`, tags: [ `Announcement` ] };
PostMetadata['124520dd-56cd-4b13-808f-7e54e885925a'] = { title: `How the Blog Works`, id: '124520dd-56cd-4b13-808f-7e54e885925a', posted: '3/23/2024', lastModified: '3/26/2024', summary: `All about how this blog of mine is currently working.`, tags: [ `C#`, `Code Generation`, `JS`, `Nuke`, `Software Engineering`, `Svelte` ] };

/**
 * Association between Post id and and its previous and next post.
 * @type {Object.<string, PostAdjacency>}
 */
export const PostAdjacency = [];
PostAdjacency['86f85de2-571b-4df4-9b39-140907351b5d'] = { previous: null, next: '124520dd-56cd-4b13-808f-7e54e885925a' };
PostAdjacency['124520dd-56cd-4b13-808f-7e54e885925a'] = { previous: '86f85de2-571b-4df4-9b39-140907351b5d', next: null };

/**
 * Latest Post Id.
 * @type {string}
 */
export const LatestPostId = '124520dd-56cd-4b13-808f-7e54e885925a';
