// WARNING: This file is generated by tools and should not be modified by hand.

/**
 * @typedef {import('$lib/types').PostIdAndPostedDate} PostIdAndPostedDate
 */

/**
 * All distinct tags used with notes.
 * @type {string[]}
 */
export const AllTags = [
	'Announcement',
];

/**
 * All distinct tags with the associated posts.
 * @type {Object.<string, string[]>}
 */
export const TagsToPostIds = [];
TagsToPostIds['Announcement'] = ['86f85de2-571b-4df4-9b39-140907351b5d'];

/**
 * All post ids to their posted dates.
 * @type {PostIdAndPostedDate[]}
 */
export const PostIdsAndPostedDate = [
	{ id: '86f85de2-571b-4df4-9b39-140907351b5d', posted: new Date(2024, 1, 22) },
];

// TODO: This file is incomplete!
