// WARNING: This file is generated by tools and should not be modified by hand.

/**
 * @typedef {import('$lib/types').PostIdAndPostedDate} PostIdAndPostedDate
 */

/**
 * All distinct tags used with notes.
 * @type {string[]}
 */
export const AllTags = [
	'Announcement',
	'C#',
	'Code Generation',
	'JS',
	'Nuke',
	'Software Engineering',
	'Svelte',
];

/**
 * All distinct tags with the associated posts.
 * @type {Object.<string, string[]>}
 */
export const TagsToPostIds = [];
TagsToPostIds['Announcement'] = ['86f85de2-571b-4df4-9b39-140907351b5d'];
TagsToPostIds['C#'] = ['124520dd-56cd-4b13-808f-7e54e885925a'];
TagsToPostIds['Code Generation'] = ['124520dd-56cd-4b13-808f-7e54e885925a'];
TagsToPostIds['JS'] = ['124520dd-56cd-4b13-808f-7e54e885925a'];
TagsToPostIds['Nuke'] = ['124520dd-56cd-4b13-808f-7e54e885925a'];
TagsToPostIds['Software Engineering'] = ['124520dd-56cd-4b13-808f-7e54e885925a'];
TagsToPostIds['Svelte'] = ['124520dd-56cd-4b13-808f-7e54e885925a'];

/**
 * All post ids to their posted dates.
 * @type {PostIdAndPostedDate[]}
 */
export const PostIdsAndPostedDate = [
	{ id: '86f85de2-571b-4df4-9b39-140907351b5d', posted: new Date(2024, 1, 22) },
	{ id: '124520dd-56cd-4b13-808f-7e54e885925a', posted: new Date(2024, 2, 19) },
];

// TODO: This file is incomplete!
